In [0]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from google.colab import files
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D 
from keras.utils import to_categorical
from keras.utils import np_utils
from keras import optimizers
import io 
import csv

In [26]:
file_train=files.upload()

Saving train.csv to train (2).csv


In [0]:
# CSV read and 1 hot , using pandas to read

# read as dataframe df_train
df_train= pd.read_csv(io.StringIO(file_train['train.csv'].decode('utf-8')))

# if none fill with NAN
df_train.fillna(0,inplace=True)


In [34]:
# debug statement to check if it works
print(df_train)

        id        sequence  label
0        0  GTAGCGGCGCATGC      1
1        1  GCCTGCCACTTCCT      1
2        2  GAGAGGAGGGGTGT      1
3        3  GGGCAGGGCCGAGG      1
4        4  AGACGGGCCGCGCC      1
5        5  CTAGGCCGGAGCGT      1
6        6  AGGAGGCGGAGGGA      1
7        7  GCGTAGGGAGGCGG      1
8        8  ACCTCTGATCATTC      1
9        9  AGCAAGAACAGCAC      1
10      10  AGCCCCCGGAGGGA      1
11      11  GCCATCGCCAACTT      1
12      12  CGAAAGATTCGAAA      1
13      13  AGGAGGGCGGGAGA      1
14      14  TGGGGCGGAGCCAT      1
15      15  CCGCTCGTCGGCTG      1
16      16  GGCCGCGCCCACCA      1
17      17  GGTGCGGCGAGCGG      1
18      18  GCGCAGCCTTATCC      1
19      19  GCGGCCAGATGGGG      1
20      20  TGGGGGCGTAGCGC      1
21      21  GCGCGGCGAGGAGA      1
22      22  GGGAGGCGTGGCGC      1
23      23  GTCGTGGGCCGTGG      1
24      24  TTTGCCCTCCCCCT      1
25      25  GCGGCGGGCCCGGG      1
26      26  CGAGGGCTGGGCCG      1
27      27  GTTGGGCCGAAACA      1
28      28  GC

In [0]:
seq=df_train['sequence']
label=df_train['label']

base={
    'A':0,
    'G':1,
    'C':2,
    'T':3
     }
enc=np.zeros( (2000,14) )

for i in range(2000):
  enc[i]= [ base[ch] for ch in seq[i]]
  enc[i]=np.transpose(enc[i])
 
encode=to_categorical(enc)



In [0]:
train_test_split?

In [0]:
# using sk's train_test_split

train_x , test_x , train_y ,test_y = train_test_split(enc , label ,test_size =0.33 )

In [38]:
# Debug check for 1hot enc
print(encode[0][:][:])
print(seq[0])

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
GTAGCGGCGCATGC


In [32]:
file_test=files.upload()

Saving test.csv to test.csv


In [0]:
## Doing the same for test data


# read as dataframe df_test
df_test= pd.read_csv(io.StringIO(file_test['test.csv'].decode('utf-8')))

# if none fill with NAN
df_test.fillna(0,inplace=True)

seq_test = df_test['sequence']

enc_test=np.zeros( (400,14) )

for i in range(400):
  enc_test[i]= [base[k] for k in seq_test[i] ]


In [0]:
model = Sequential()
model.add(Dense(28, input_dim =14, activation ='relu'))
model.add(Dense(15, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))
          

In [84]:
## Changing the optimizer
sgd = optimizers.SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
model.compile (  optimizer = 'sgd'  ,loss ='binary_crossentropy' , metrics=['accuracy'])
model.fit(train_x , train_y , epochs = 400, batch_size = 10)

Epoch 1/400
1340/1340 [==============================] - 0s 288us/step - loss: 0.7341 - acc: 0.4396
Epoch 2/400
1340/1340 [==============================] - 0s 129us/step - loss: 0.6884 - acc: 0.4881
Epoch 3/400
1340/1340 [==============================] - 0s 128us/step - loss: 0.6771 - acc: 0.5485
Epoch 4/400
1340/1340 [==============================] - 0s 127us/step - loss: 0.6686 - acc: 0.5993
Epoch 5/400
1340/1340 [==============================] - 0s 127us/step - loss: 0.6610 - acc: 0.6164
Epoch 6/400
1340/1340 [==============================] - 0s 133us/step - loss: 0.6522 - acc: 0.6246
Epoch 7/400
1340/1340 [==============================] - 0s 127us/step - loss: 0.6450 - acc: 0.6328
Epoch 8/400
1340/1340 [==============================] - 0s 130us/step - loss: 0.6368 - acc: 0.6507
Epoch 9/400
1340/1340 [==============================] - 0s 136us/step - loss: 0.6285 - acc: 0.6642
Epoch 10/400
1340/1340 [==============================] - 0s 128us/step - loss: 0.6191 - acc: 0.6813

1340/1340 [==============================] - 0s 165us/step - loss: 0.5355 - acc: 0.7597
Epoch 20/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.5270 - acc: 0.7672
Epoch 21/400
1340/1340 [==============================] - 0s 154us/step - loss: 0.5171 - acc: 0.7709
Epoch 22/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.5090 - acc: 0.7784
Epoch 23/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.4985 - acc: 0.7739
Epoch 24/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.4870 - acc: 0.7896
Epoch 25/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.4847 - acc: 0.7821
Epoch 26/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.4678 - acc: 0.8015
Epoch 27/400
1340/1340 [==============================] - 0s 156us/step - loss: 0.4635 - acc: 0.7925
Epoch 28/400
1340/1340 [==============================] - 0s 156us/step - loss: 0.4510 - acc: 0.8075
Epo

1340/1340 [==============================] - 0s 148us/step - loss: 0.3966 - acc: 0.8246
Epoch 37/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.3938 - acc: 0.8358
Epoch 38/400
1340/1340 [==============================] - 0s 169us/step - loss: 0.3844 - acc: 0.8425
Epoch 39/400
1340/1340 [==============================] - 0s 140us/step - loss: 0.3804 - acc: 0.8403
Epoch 40/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.3723 - acc: 0.8358
Epoch 41/400
1340/1340 [==============================] - 0s 136us/step - loss: 0.3745 - acc: 0.8410
Epoch 42/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.3711 - acc: 0.8478
Epoch 43/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.3632 - acc: 0.8478
Epoch 44/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.3623 - acc: 0.8515
Epoch 45/400
1340/1340 [==============================] - 0s 153us/step - loss: 0.3582 - acc: 0.8552
Epo

1340/1340 [==============================] - 0s 151us/step - loss: 0.3209 - acc: 0.8687
Epoch 55/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.3281 - acc: 0.8575
Epoch 56/400
1340/1340 [==============================] - 0s 154us/step - loss: 0.3246 - acc: 0.8597
Epoch 57/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.3187 - acc: 0.8694
Epoch 58/400
1340/1340 [==============================] - 0s 155us/step - loss: 0.3199 - acc: 0.8672
Epoch 59/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.3192 - acc: 0.8604
Epoch 60/400
1340/1340 [==============================] - 0s 142us/step - loss: 0.3188 - acc: 0.8694
Epoch 61/400
1340/1340 [==============================] - 0s 162us/step - loss: 0.3021 - acc: 0.8769
Epoch 62/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.3082 - acc: 0.8664
Epoch 63/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.3042 - acc: 0.8821
Epo

1340/1340 [==============================] - 0s 148us/step - loss: 0.2947 - acc: 0.8806
Epoch 73/400
1340/1340 [==============================] - 0s 143us/step - loss: 0.3058 - acc: 0.8731
Epoch 74/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.2898 - acc: 0.8828
Epoch 75/400
1340/1340 [==============================] - 0s 157us/step - loss: 0.2914 - acc: 0.8836
Epoch 76/400
1340/1340 [==============================] - 0s 163us/step - loss: 0.2908 - acc: 0.8776
Epoch 77/400
1340/1340 [==============================] - 0s 148us/step - loss: 0.2887 - acc: 0.8769
Epoch 78/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.2801 - acc: 0.8806
Epoch 79/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.2969 - acc: 0.8709
Epoch 80/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2725 - acc: 0.8903
Epoch 81/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.2735 - acc: 0.8828
Epo

1340/1340 [==============================] - 0s 144us/step - loss: 0.2628 - acc: 0.8955
Epoch 91/400
1340/1340 [==============================] - 0s 161us/step - loss: 0.2591 - acc: 0.9022
Epoch 92/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2573 - acc: 0.9015
Epoch 93/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.2590 - acc: 0.8985
Epoch 94/400
1340/1340 [==============================] - 0s 148us/step - loss: 0.2627 - acc: 0.8925
Epoch 95/400
1340/1340 [==============================] - 0s 143us/step - loss: 0.2504 - acc: 0.9000
Epoch 96/400
1340/1340 [==============================] - 0s 155us/step - loss: 0.2401 - acc: 0.9045
Epoch 97/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2582 - acc: 0.8888
Epoch 98/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2489 - acc: 0.9097
Epoch 99/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2420 - acc: 0.9030
Epo

Epoch 108/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.2354 - acc: 0.9090
Epoch 109/400
1340/1340 [==============================] - 0s 158us/step - loss: 0.2429 - acc: 0.8985
Epoch 110/400
1340/1340 [==============================] - 0s 154us/step - loss: 0.2360 - acc: 0.9097
Epoch 111/400
1340/1340 [==============================] - 0s 141us/step - loss: 0.2290 - acc: 0.9179
Epoch 112/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2397 - acc: 0.9045
Epoch 113/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.2337 - acc: 0.9030
Epoch 114/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.2329 - acc: 0.9030
Epoch 115/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.2336 - acc: 0.9052
Epoch 116/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.2315 - acc: 0.9067
Epoch 117/400
1340/1340 [==============================] - 0s 149us/step - loss: 0


1340/1340 [==============================] - 0s 145us/step - loss: 0.2146 - acc: 0.9149
Epoch 127/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.2264 - acc: 0.9209
Epoch 128/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.2208 - acc: 0.9149
Epoch 129/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.2259 - acc: 0.9104
Epoch 130/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.2159 - acc: 0.9164
Epoch 131/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.2166 - acc: 0.9179
Epoch 132/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2130 - acc: 0.9201
Epoch 133/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2179 - acc: 0.9127
Epoch 134/400
1340/1340 [==============================] - 0s 148us/step - loss: 0.2141 - acc: 0.9172
Epoch 135/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.2145 - acc: 

1340/1340 [==============================] - 0s 150us/step - loss: 0.2081 - acc: 0.9157
Epoch 145/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.2061 - acc: 0.9209
Epoch 146/400
1340/1340 [==============================] - 0s 155us/step - loss: 0.2107 - acc: 0.9179
Epoch 147/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.2112 - acc: 0.9231
Epoch 148/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2015 - acc: 0.9231
Epoch 149/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.2058 - acc: 0.9239
Epoch 150/400
1340/1340 [==============================] - 0s 155us/step - loss: 0.2019 - acc: 0.9276
Epoch 151/400
1340/1340 [==============================] - 0s 159us/step - loss: 0.2065 - acc: 0.9216
Epoch 152/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2021 - acc: 0.9246
Epoch 153/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.2051 - acc: 0

Epoch 162/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1858 - acc: 0.9246
Epoch 163/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1889 - acc: 0.9269
Epoch 164/400
1340/1340 [==============================] - 0s 153us/step - loss: 0.1830 - acc: 0.9313
Epoch 165/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.2089 - acc: 0.9172
Epoch 166/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.2051 - acc: 0.9179
Epoch 167/400
1340/1340 [==============================] - 0s 148us/step - loss: 0.1957 - acc: 0.9284
Epoch 168/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1930 - acc: 0.9261
Epoch 169/400
1340/1340 [==============================] - 0s 157us/step - loss: 0.1814 - acc: 0.9261
Epoch 170/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.2036 - acc: 0.9201
Epoch 171/400
1340/1340 [==============================] - 0s 148us/step - loss: 0

1340/1340 [==============================] - 0s 151us/step - loss: 0.2008 - acc: 0.9231
Epoch 180/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1819 - acc: 0.9306
Epoch 181/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1815 - acc: 0.9291
Epoch 182/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.2010 - acc: 0.9224
Epoch 183/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1764 - acc: 0.9291
Epoch 184/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1927 - acc: 0.9224
Epoch 185/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.1850 - acc: 0.9261
Epoch 186/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1801 - acc: 0.9328
Epoch 187/400
1340/1340 [==============================] - 0s 153us/step - loss: 0.1786 - acc: 0.9328
Epoch 188/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1740 - acc: 0

1340/1340 [==============================] - 0s 162us/step - loss: 0.1823 - acc: 0.9299
Epoch 197/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1637 - acc: 0.9418
Epoch 198/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1684 - acc: 0.9328
Epoch 199/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1831 - acc: 0.9306
Epoch 200/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.1670 - acc: 0.9351
Epoch 201/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1735 - acc: 0.9261
Epoch 202/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1734 - acc: 0.9373
Epoch 203/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1640 - acc: 0.9381
Epoch 204/400
1340/1340 [==============================] - 0s 153us/step - loss: 0.1857 - acc: 0.9239
Epoch 205/400
1340/1340 [==============================] - 0s 139us/step - loss: 0.1827 - acc: 0

1340/1340 [==============================] - 0s 147us/step - loss: 0.1682 - acc: 0.9396
Epoch 214/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1811 - acc: 0.9231
Epoch 215/400
1340/1340 [==============================] - 0s 153us/step - loss: 0.1750 - acc: 0.9313
Epoch 216/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1635 - acc: 0.9328
Epoch 217/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1685 - acc: 0.9343
Epoch 218/400
1340/1340 [==============================] - 0s 165us/step - loss: 0.1596 - acc: 0.9328
Epoch 219/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1848 - acc: 0.9231
Epoch 220/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.1708 - acc: 0.9366
Epoch 221/400
1340/1340 [==============================] - 0s 153us/step - loss: 0.1760 - acc: 0.9381
Epoch 222/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1559 - acc: 0

1340/1340 [==============================] - 0s 151us/step - loss: 0.1694 - acc: 0.9313
Epoch 232/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1592 - acc: 0.9388
Epoch 233/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1545 - acc: 0.9455
Epoch 234/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1462 - acc: 0.9418
Epoch 235/400
1340/1340 [==============================] - 0s 156us/step - loss: 0.1644 - acc: 0.9381
Epoch 236/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.1448 - acc: 0.9507
Epoch 237/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1546 - acc: 0.9410
Epoch 238/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1709 - acc: 0.9321
Epoch 239/400
1340/1340 [==============================] - 0s 148us/step - loss: 0.1643 - acc: 0.9321
Epoch 240/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1597 - acc: 0

1340/1340 [==============================] - 0s 148us/step - loss: 0.1789 - acc: 0.9343
Epoch 250/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.1536 - acc: 0.9403
Epoch 251/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.1429 - acc: 0.9455
Epoch 252/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.1492 - acc: 0.9396
Epoch 253/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1499 - acc: 0.9366
Epoch 254/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1436 - acc: 0.9418
Epoch 255/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.1423 - acc: 0.9418
Epoch 256/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1570 - acc: 0.9366
Epoch 257/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.1455 - acc: 0.9396
Epoch 258/400
1340/1340 [==============================] - 0s 141us/step - loss: 0.1518 - acc: 0

1340/1340 [==============================] - 0s 136us/step - loss: 0.1452 - acc: 0.9463
Epoch 268/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1382 - acc: 0.9485
Epoch 269/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1408 - acc: 0.9455
Epoch 270/400
1340/1340 [==============================] - 0s 142us/step - loss: 0.1404 - acc: 0.9478
Epoch 271/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1330 - acc: 0.9493
Epoch 272/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.1391 - acc: 0.9470
Epoch 273/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.1532 - acc: 0.9440
Epoch 274/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.1379 - acc: 0.9448
Epoch 275/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1364 - acc: 0.9478
Epoch 276/400
1340/1340 [==============================] - 0s 153us/step - loss: 0.1540 - acc: 0

Epoch 285/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.1337 - acc: 0.9522
Epoch 286/400
1340/1340 [==============================] - 0s 139us/step - loss: 0.1435 - acc: 0.9463
Epoch 287/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.1375 - acc: 0.9440
Epoch 288/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1404 - acc: 0.9507
Epoch 289/400
1340/1340 [==============================] - 0s 143us/step - loss: 0.1400 - acc: 0.9410
Epoch 290/400
1340/1340 [==============================] - 0s 140us/step - loss: 0.1354 - acc: 0.9493
Epoch 291/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1425 - acc: 0.9425
Epoch 292/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.1459 - acc: 0.9448
Epoch 293/400
1340/1340 [==============================] - 0s 148us/step - loss: 0.1232 - acc: 0.9537
Epoch 294/400
1340/1340 [==============================] - 0s 148us/step - loss: 0

Epoch 303/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1225 - acc: 0.9552
Epoch 304/400
1340/1340 [==============================] - 0s 159us/step - loss: 0.1318 - acc: 0.9507
Epoch 305/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1407 - acc: 0.9463
Epoch 306/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1301 - acc: 0.9455
Epoch 307/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1297 - acc: 0.9478
Epoch 308/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1297 - acc: 0.9507
Epoch 309/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1327 - acc: 0.9545
Epoch 310/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1207 - acc: 0.9522
Epoch 311/400
1340/1340 [==============================] - 0s 140us/step - loss: 0.1345 - acc: 0.9463
Epoch 312/400
1340/1340 [==============================] - 0s 139us/step - loss: 0

1340/1340 [==============================] - 0s 166us/step - loss: 0.1171 - acc: 0.9560
Epoch 321/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1316 - acc: 0.9493
Epoch 322/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.1264 - acc: 0.9537
Epoch 323/400
1340/1340 [==============================] - 0s 155us/step - loss: 0.1121 - acc: 0.9575
Epoch 324/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.1212 - acc: 0.9545
Epoch 325/400
1340/1340 [==============================] - 0s 143us/step - loss: 0.1124 - acc: 0.9537
Epoch 326/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.1194 - acc: 0.9545
Epoch 327/400
1340/1340 [==============================] - 0s 154us/step - loss: 0.1167 - acc: 0.9530
Epoch 328/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1192 - acc: 0.9552
Epoch 329/400
1340/1340 [==============================] - 0s 156us/step - loss: 0.1223 - acc: 0


1340/1340 [==============================] - 0s 152us/step - loss: 0.1155 - acc: 0.9604
Epoch 339/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1276 - acc: 0.9545
Epoch 340/400
1340/1340 [==============================] - 0s 154us/step - loss: 0.1234 - acc: 0.9515
Epoch 341/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1137 - acc: 0.9582
Epoch 342/400
1340/1340 [==============================] - 0s 154us/step - loss: 0.1131 - acc: 0.9582
Epoch 343/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.1233 - acc: 0.9485
Epoch 344/400
1340/1340 [==============================] - 0s 142us/step - loss: 0.1056 - acc: 0.9604
Epoch 345/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.0957 - acc: 0.9657
Epoch 346/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.1087 - acc: 0.9582
Epoch 347/400
1340/1340 [==============================] - 0s 146us/step - loss: 0.1133 - acc: 

1340/1340 [==============================] - 0s 141us/step - loss: 0.1064 - acc: 0.9612
Epoch 356/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.1049 - acc: 0.9545
Epoch 357/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1156 - acc: 0.9485
Epoch 358/400
1340/1340 [==============================] - 0s 143us/step - loss: 0.1012 - acc: 0.9619
Epoch 359/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.0991 - acc: 0.9649
Epoch 360/400
1340/1340 [==============================] - 0s 162us/step - loss: 0.1207 - acc: 0.9530
Epoch 361/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1114 - acc: 0.9567
Epoch 362/400
1340/1340 [==============================] - 0s 147us/step - loss: 0.1031 - acc: 0.9604
Epoch 363/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.0965 - acc: 0.9642
Epoch 364/400
1340/1340 [==============================] - 0s 141us/step - loss: 0.0972 - acc: 0

1340/1340 [==============================] - 0s 143us/step - loss: 0.0904 - acc: 0.9701
Epoch 373/400
1340/1340 [==============================] - 0s 163us/step - loss: 0.1093 - acc: 0.9567
Epoch 374/400
1340/1340 [==============================] - 0s 142us/step - loss: 0.1071 - acc: 0.9612
Epoch 375/400
1340/1340 [==============================] - 0s 151us/step - loss: 0.1145 - acc: 0.9545
Epoch 376/400
1340/1340 [==============================] - 0s 153us/step - loss: 0.1091 - acc: 0.9582
Epoch 377/400
1340/1340 [==============================] - 0s 143us/step - loss: 0.1013 - acc: 0.9590
Epoch 378/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1075 - acc: 0.9612
Epoch 379/400
1340/1340 [==============================] - 0s 154us/step - loss: 0.0966 - acc: 0.9672
Epoch 380/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.1015 - acc: 0.9657
Epoch 381/400
1340/1340 [==============================] - 0s 148us/step - loss: 0.0981 - acc: 0

1340/1340 [==============================] - 0s 149us/step - loss: 0.0893 - acc: 0.9642
Epoch 391/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1004 - acc: 0.9664
Epoch 392/400
1340/1340 [==============================] - 0s 150us/step - loss: 0.1356 - acc: 0.9463
Epoch 393/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.1195 - acc: 0.9567
Epoch 394/400
1340/1340 [==============================] - 0s 145us/step - loss: 0.1028 - acc: 0.9627
Epoch 395/400
1340/1340 [==============================] - 0s 152us/step - loss: 0.0938 - acc: 0.9687
Epoch 396/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.0879 - acc: 0.9672
Epoch 397/400
1340/1340 [==============================] - 0s 144us/step - loss: 0.1257 - acc: 0.9478
Epoch 398/400
1340/1340 [==============================] - 0s 149us/step - loss: 0.1095 - acc: 0.9590
Epoch 399/400
1340/1340 [==============================] - 0s 141us/step - loss: 0.1008 - acc: 0

In [59]:
## without changing optimizer , gave a value of 0.773 
model.compile (  optimizer = 'sgd'  ,loss ='binary_crossentropy' , metrics=['accuracy'])
model.fit(train_x , train_y , epochs = 200, batch_size = 15)

Epoch 1/200
1340/1340 [==============================] - 0s 180us/step - loss: 0.3246 - acc: 0.8649
Epoch 2/200
1340/1340 [==============================] - 0s 85us/step - loss: 0.3254 - acc: 0.8709
Epoch 3/200
1340/1340 [==============================] - 0s 87us/step - loss: 0.3302 - acc: 0.8612
Epoch 4/200
1340/1340 [==============================] - 0s 85us/step - loss: 0.3246 - acc: 0.8604
Epoch 5/200
1340/1340 [==============================] - 0s 83us/step - loss: 0.3178 - acc: 0.8731
Epoch 6/200
1340/1340 [==============================] - 0s 86us/step - loss: 0.3263 - acc: 0.8604
Epoch 7/200
1340/1340 [==============================] - 0s 87us/step - loss: 0.3274 - acc: 0.8642
Epoch 8/200
1340/1340 [==============================] - 0s 86us/step - loss: 0.3183 - acc: 0.8716
Epoch 9/200
1340/1340 [==============================] - 0s 90us/step - loss: 0.3178 - acc: 0.8619
Epoch 10/200
1340/1340 [==============================] - 0s 77us/step - loss: 0.3115 - acc: 0.8716
Epoch 11

Epoch 23/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.3053 - acc: 0.8657
Epoch 24/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2966 - acc: 0.8731
Epoch 25/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2995 - acc: 0.8761
Epoch 26/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.3008 - acc: 0.8739
Epoch 27/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2948 - acc: 0.8724
Epoch 28/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.3013 - acc: 0.8634
Epoch 29/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.3022 - acc: 0.8754
Epoch 30/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2904 - acc: 0.8851
Epoch 31/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2958 - acc: 0.8784
Epoch 32/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.2966 - acc:

1340/1340 [==============================] - 0s 102us/step - loss: 0.2837 - acc: 0.8821
Epoch 45/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2817 - acc: 0.8851
Epoch 46/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2747 - acc: 0.8910
Epoch 47/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2800 - acc: 0.8799
Epoch 48/200
1340/1340 [==============================] - 0s 112us/step - loss: 0.2806 - acc: 0.8896
Epoch 49/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.2749 - acc: 0.8955
Epoch 50/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2795 - acc: 0.8910
Epoch 51/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2833 - acc: 0.8843
Epoch 52/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2728 - acc: 0.8903
Epoch 53/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2747 - acc: 0.8933
Epo

1340/1340 [==============================] - 0s 96us/step - loss: 0.2775 - acc: 0.8828
Epoch 66/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2720 - acc: 0.8858
Epoch 67/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2675 - acc: 0.8866
Epoch 68/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2649 - acc: 0.8918
Epoch 69/200
1340/1340 [==============================] - 0s 97us/step - loss: 0.2634 - acc: 0.8948
Epoch 70/200
1340/1340 [==============================] - 0s 99us/step - loss: 0.2728 - acc: 0.8858
Epoch 71/200
1340/1340 [==============================] - 0s 109us/step - loss: 0.2682 - acc: 0.8903
Epoch 72/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2668 - acc: 0.8903
Epoch 73/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2632 - acc: 0.8970
Epoch 74/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2594 - acc: 0.8925
Epoch 7

1340/1340 [==============================] - 0s 104us/step - loss: 0.2543 - acc: 0.8940
Epoch 87/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2635 - acc: 0.8873
Epoch 88/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2587 - acc: 0.8978
Epoch 89/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2464 - acc: 0.8948
Epoch 90/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.2594 - acc: 0.8910
Epoch 91/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2594 - acc: 0.8955
Epoch 92/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2527 - acc: 0.8970
Epoch 93/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2594 - acc: 0.8940
Epoch 94/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2569 - acc: 0.8955
Epoch 95/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2573 - acc: 0.8896
Epo

1340/1340 [==============================] - 0s 110us/step - loss: 0.2427 - acc: 0.9045
Epoch 108/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2520 - acc: 0.9007
Epoch 109/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2438 - acc: 0.8978
Epoch 110/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.2507 - acc: 0.8993
Epoch 111/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2439 - acc: 0.8985
Epoch 112/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2464 - acc: 0.8978
Epoch 113/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2489 - acc: 0.8963
Epoch 114/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.2499 - acc: 0.8970
Epoch 115/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2445 - acc: 0.9000
Epoch 116/200
1340/1340 [==============================] - 0s 108us/step - loss: 0.2475 - acc: 0.

1340/1340 [==============================] - 0s 105us/step - loss: 0.2352 - acc: 0.9067
Epoch 129/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2344 - acc: 0.9030
Epoch 130/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2443 - acc: 0.9037
Epoch 131/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2386 - acc: 0.8978
Epoch 132/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2369 - acc: 0.9052
Epoch 133/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2330 - acc: 0.9104
Epoch 134/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2381 - acc: 0.8978
Epoch 135/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2415 - acc: 0.8896
Epoch 136/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2349 - acc: 0.9037
Epoch 137/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2370 - acc: 0.90

1340/1340 [==============================] - 0s 103us/step - loss: 0.2326 - acc: 0.9000
Epoch 150/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.2256 - acc: 0.9090
Epoch 151/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2267 - acc: 0.9060
Epoch 152/200
1340/1340 [==============================] - 0s 109us/step - loss: 0.2367 - acc: 0.9075
Epoch 153/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2313 - acc: 0.9015
Epoch 154/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2220 - acc: 0.9112
Epoch 155/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2273 - acc: 0.9075
Epoch 156/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2282 - acc: 0.9075
Epoch 157/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2316 - acc: 0.9075
Epoch 158/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2262 - acc: 0.

1340/1340 [==============================] - 0s 105us/step - loss: 0.2150 - acc: 0.9142
Epoch 171/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2187 - acc: 0.9157
Epoch 172/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2238 - acc: 0.9067
Epoch 173/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2200 - acc: 0.9060
Epoch 174/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2228 - acc: 0.9067
Epoch 175/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2266 - acc: 0.8955
Epoch 176/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2196 - acc: 0.9022
Epoch 177/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2221 - acc: 0.9097
Epoch 178/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2143 - acc: 0.9090
Epoch 179/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2232 - acc: 0.908

1340/1340 [==============================] - 0s 100us/step - loss: 0.2107 - acc: 0.9149
Epoch 192/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2206 - acc: 0.9030
Epoch 193/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2091 - acc: 0.9112
Epoch 194/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2099 - acc: 0.9179
Epoch 195/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2117 - acc: 0.9104
Epoch 196/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2131 - acc: 0.9067
Epoch 197/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2207 - acc: 0.9052
Epoch 198/200
1340/1340 [==============================] - 0s 97us/step - loss: 0.2099 - acc: 0.9187
Epoch 199/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2100 - acc: 0.9090
Epoch 200/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2097 - acc: 0.909

In [62]:
# without changing optimizer
trained_out = model.evaluate (test_x , test_y)
print(trained_out)

660/660 [==============================] - 0s 34us/step
[0.49056715206666424, 0.8121212121212121]


In [85]:
# After Changing optimizer
trained_out = model.evaluate (test_x , test_y)
print(trained_out)

# seems like overfitting

660/660 [==============================] - 0s 147us/step
[0.7774025349905996, 0.801515150792671]


In [86]:
predic = np.round( model.predict(enc_test) ) 
print(predic)

[[1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.

In [0]:
save_test =pd.DataFrame(predic)
save_test.to_csv("test_check_1.csv")
files.download("test_check_1.csv")


In [0]:
Dense?