In [0]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from google.colab import files
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Embedding,LSTM
from keras.layers import Conv1D, GlobalAveragePooling1D, MaxPooling1D
from keras.layers import Convolution2D 
from keras.utils import to_categorical
from keras.utils import np_utils
from keras import optimizers
import io 
import csv

In [4]:
file_train=files.upload()

Saving train.csv to train.csv


In [0]:
# CSV read and 1 hot , using pandas to read

# read as dataframe df_train
df_train= pd.read_csv(io.StringIO(file_train['train.csv'].decode('utf-8')))

# if none fill with NAN
df_train.fillna(0,inplace=True)


In [6]:
# debug statement to check if it works
print(df_train)

        id        sequence  label
0        0  GTAGCGGCGCATGC      1
1        1  GCCTGCCACTTCCT      1
2        2  GAGAGGAGGGGTGT      1
3        3  GGGCAGGGCCGAGG      1
4        4  AGACGGGCCGCGCC      1
5        5  CTAGGCCGGAGCGT      1
6        6  AGGAGGCGGAGGGA      1
7        7  GCGTAGGGAGGCGG      1
8        8  ACCTCTGATCATTC      1
9        9  AGCAAGAACAGCAC      1
10      10  AGCCCCCGGAGGGA      1
11      11  GCCATCGCCAACTT      1
12      12  CGAAAGATTCGAAA      1
13      13  AGGAGGGCGGGAGA      1
14      14  TGGGGCGGAGCCAT      1
15      15  CCGCTCGTCGGCTG      1
16      16  GGCCGCGCCCACCA      1
17      17  GGTGCGGCGAGCGG      1
18      18  GCGCAGCCTTATCC      1
19      19  GCGGCCAGATGGGG      1
20      20  TGGGGGCGTAGCGC      1
21      21  GCGCGGCGAGGAGA      1
22      22  GGGAGGCGTGGCGC      1
23      23  GTCGTGGGCCGTGG      1
24      24  TTTGCCCTCCCCCT      1
25      25  GCGGCGGGCCCGGG      1
26      26  CGAGGGCTGGGCCG      1
27      27  GTTGGGCCGAAACA      1
28      28  GC

In [0]:
seq=df_train['sequence']
label=df_train['label']

base={
    'A':0,
    'G':1,
    'C':2,
    'T':3
     }
enc=np.zeros( (2000,14) )

for i in range(2000):
  enc[i]= [ base[ch] for ch in seq[i]]
  enc[i]=np.transpose(enc[i])
 
encode=to_categorical(enc)



In [0]:
train_test_split?

In [0]:
# using sk's train_test_split

train_x , test_x , train_y ,test_y = train_test_split(enc , label ,test_size =0.33 )

In [9]:
# Debug check for 1hot enc
print(encode[0][:][:])
print(seq[0])

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
GTAGCGGCGCATGC


In [10]:
file_test=files.upload()

Saving test.csv to test.csv


In [0]:
## Doing the same for test data


# read as dataframe df_test
df_test= pd.read_csv(io.StringIO(file_test['test.csv'].decode('utf-8')))

# if none fill with NAN
df_test.fillna(0,inplace=True)

seq_test = df_test['sequence']

enc_test=np.zeros( (400,14) )

for i in range(400):
  enc_test[i]= [base[k] for k in seq_test[i] ]


In [0]:
## basic ANN
model = Sequential()
model.add(Dense(20, input_dim =14, activation ='relu'))
model.add(Dense(14, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))
          

In [36]:
## 1D conv
model = Sequential()
model.add(Conv1D(64, 1, activation='relu', input_shape=(1340, 14)))
model.add(Conv1D(64, 1, activation='relu'))
model.add(MaxPooling1D(1))
model.add(Conv1D(128, 1, activation='relu'))
model.add(Conv1D(128, 1, activation='relu'))
model.add(GlobalAveragePooling1D())
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=16, epochs=50)


ValueError: ignored

In [28]:
## LSTM

model = Sequential()
model.add(Embedding(14, output_dim=128))
model.add(LSTM(64))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=16, epochs=50)

Epoch 1/50
1340/1340 [==============================] - 2s 1ms/step - loss: 0.3821 - acc: 0.8351
Epoch 2/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3319 - acc: 0.8522
Epoch 3/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3279 - acc: 0.8560
Epoch 4/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3212 - acc: 0.8612
Epoch 5/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3274 - acc: 0.8530
Epoch 6/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3232 - acc: 0.8612
Epoch 7/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3166 - acc: 0.8582
Epoch 8/50
1340/1340 [==============================] - 1s 998us/step - loss: 0.3210 - acc: 0.8634
Epoch 9/50
1104/1340 [=======================>......] - ETA: 0s - loss: 0.3263 - acc: 0.8623

1340/1340 [==============================] - 1s 1ms/step - loss: 0.3215 - acc: 0.8604
Epoch 10/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3175 - acc: 0.8634
Epoch 11/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3216 - acc: 0.8642
Epoch 12/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3174 - acc: 0.8642
Epoch 13/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3108 - acc: 0.8627
Epoch 14/50
1340/1340 [==============================] - 1s 989us/step - loss: 0.3154 - acc: 0.8657
Epoch 15/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3148 - acc: 0.8694
Epoch 16/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3125 - acc: 0.8657
Epoch 17/50
1340/1340 [==============================] - 1s 981us/step - loss: 0.3172 - acc: 0.8590


Epoch 18/50
1340/1340 [==============================] - 1s 995us/step - loss: 0.3127 - acc: 0.8709
Epoch 19/50
1340/1340 [==============================] - 1s 985us/step - loss: 0.3069 - acc: 0.8672
Epoch 20/50
1340/1340 [==============================] - 1s 995us/step - loss: 0.3027 - acc: 0.8799
Epoch 21/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3035 - acc: 0.8634
Epoch 22/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3016 - acc: 0.8746
Epoch 23/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3009 - acc: 0.8709
Epoch 24/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2965 - acc: 0.8828
Epoch 25/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2881 - acc: 0.8813
Epoch 26/50
1088/1340 [=======================>......] - ETA: 0s - loss: 0.2843 - acc: 0.8842

1340/1340 [==============================] - 1s 1ms/step - loss: 0.2868 - acc: 0.8799
Epoch 27/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2879 - acc: 0.8716
Epoch 28/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2869 - acc: 0.8784
Epoch 29/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2828 - acc: 0.8866
Epoch 30/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2909 - acc: 0.8784
Epoch 31/50
1340/1340 [==============================] - 1s 991us/step - loss: 0.2844 - acc: 0.8866
Epoch 32/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2808 - acc: 0.8806
Epoch 33/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2781 - acc: 0.8828
Epoch 34/50
1152/1340 [========================>.....] - ETA: 0s - loss: 0.2813 - acc: 0.8819

1340/1340 [==============================] - 1s 1ms/step - loss: 0.2776 - acc: 0.8799
Epoch 35/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2801 - acc: 0.8873
Epoch 36/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2735 - acc: 0.8799
Epoch 37/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2738 - acc: 0.8955
Epoch 38/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2698 - acc: 0.8843
Epoch 39/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2655 - acc: 0.8843
Epoch 40/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2657 - acc: 0.8903
Epoch 41/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2593 - acc: 0.8978
Epoch 42/50
1168/1340 [=========================>....] - ETA: 0s - loss: 0.2524 - acc: 0.9024

1340/1340 [==============================] - 1s 996us/step - loss: 0.2529 - acc: 0.9015
Epoch 43/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2507 - acc: 0.8978
Epoch 44/50
1340/1340 [==============================] - 1s 996us/step - loss: 0.2529 - acc: 0.8940
Epoch 45/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2508 - acc: 0.9000
Epoch 46/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2438 - acc: 0.9007
Epoch 47/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2374 - acc: 0.9060
Epoch 48/50
1340/1340 [==============================] - 1s 999us/step - loss: 0.2344 - acc: 0.9112
Epoch 49/50
1340/1340 [==============================] - 1s 1ms/step - loss: 0.2332 - acc: 0.9052
Epoch 50/50
1216/1340 [==========================>...] - ETA: 0s - loss: 0.2407 - acc: 0.8980

1340/1340 [==============================] - 1s 1ms/step - loss: 0.2383 - acc: 0.8993


In [55]:
## LSTM  iteration 2

model = Sequential()
model.add(Embedding(14, output_dim=128))
model.add(LSTM(64))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=16, epochs=20)

Epoch 1/20
1340/1340 [==============================] - 3s 2ms/step - loss: 0.3952 - acc: 0.8351
Epoch 2/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3318 - acc: 0.8604
Epoch 3/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3290 - acc: 0.8590
Epoch 4/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3213 - acc: 0.8657
Epoch 5/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3240 - acc: 0.8552
Epoch 6/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3220 - acc: 0.8642
Epoch 7/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3255 - acc: 0.8597
Epoch 8/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3226 - acc: 0.8590
Epoch 9/20
 896/1340 [===================>..........] - ETA: 0s - loss: 0.3440 - acc: 0.8460

1340/1340 [==============================] - 1s 1ms/step - loss: 0.3223 - acc: 0.8612
Epoch 10/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3240 - acc: 0.8649
Epoch 11/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3136 - acc: 0.8634
Epoch 12/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3179 - acc: 0.8582
Epoch 13/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3221 - acc: 0.8657
Epoch 14/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3117 - acc: 0.8597
Epoch 15/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3192 - acc: 0.8642
Epoch 16/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3120 - acc: 0.8619
Epoch 17/20
1008/1340 [=====================>........] - ETA: 0s - loss: 0.3035 - acc: 0.8681

1340/1340 [==============================] - 1s 1ms/step - loss: 0.3094 - acc: 0.8672
Epoch 18/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3145 - acc: 0.8664
Epoch 19/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3107 - acc: 0.8716
Epoch 20/20
1340/1340 [==============================] - 1s 1ms/step - loss: 0.3107 - acc: 0.8664


In [19]:
## Changing the optimizer
## sgd = optimizers.SGD(lr=0.001, decay=1e-6, momentum=0.8, nesterov=True)
rms=optimizers.RMSprop(lr=0.001, rho=0.9, epsilon=None, decay=0.0)
model.compile (  optimizer = sgd  ,loss ='binary_crossentropy' , metrics=['accuracy'])
model.fit(train_x , train_y , epochs = 400, batch_size = 30)

Epoch 1/400
1340/1340 [==============================] - 0s 106us/step - loss: 0.0764 - acc: 0.9821
Epoch 2/400
1340/1340 [==============================] - 0s 39us/step - loss: 0.0748 - acc: 0.9813
Epoch 3/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0762 - acc: 0.9858
Epoch 4/400
1340/1340 [==============================] - 0s 45us/step - loss: 0.0734 - acc: 0.9873
Epoch 5/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0749 - acc: 0.9843
Epoch 6/400
1340/1340 [==============================] - 0s 45us/step - loss: 0.0748 - acc: 0.9866
Epoch 7/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0733 - acc: 0.9843
Epoch 8/400
1340/1340 [==============================] - 0s 39us/step - loss: 0.0742 - acc: 0.9813
Epoch 9/400
1340/1340 [==============================] - 0s 45us/step - loss: 0.0717 - acc: 0.9843
Epoch 10/400
1340/1340 [==============================] - 0s 45us/step - loss: 0.0744 - acc: 0.9843
Epoch 11

1340/1340 [==============================] - 0s 43us/step - loss: 0.0750 - acc: 0.9836
Epoch 29/400
1340/1340 [==============================] - 0s 39us/step - loss: 0.0727 - acc: 0.9866
Epoch 30/400
1340/1340 [==============================] - 0s 43us/step - loss: 0.0731 - acc: 0.9881
Epoch 31/400
1340/1340 [==============================] - 0s 39us/step - loss: 0.0726 - acc: 0.9866
Epoch 32/400
1340/1340 [==============================] - 0s 44us/step - loss: 0.0725 - acc: 0.9873
Epoch 33/400
1340/1340 [==============================] - 0s 40us/step - loss: 0.0749 - acc: 0.9858
Epoch 34/400
1340/1340 [==============================] - 0s 45us/step - loss: 0.0742 - acc: 0.9821
Epoch 35/400
1340/1340 [==============================] - 0s 38us/step - loss: 0.0737 - acc: 0.9836
Epoch 36/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0746 - acc: 0.9843
Epoch 37/400
1340/1340 [==============================] - 0s 39us/step - loss: 0.0731 - acc: 0.9821
Epoch 38/400


1340/1340 [==============================] - 0s 48us/step - loss: 0.0720 - acc: 0.9858
Epoch 54/400
1340/1340 [==============================] - 0s 56us/step - loss: 0.0740 - acc: 0.9843
Epoch 55/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0717 - acc: 0.9836
Epoch 56/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0716 - acc: 0.9873
Epoch 57/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0724 - acc: 0.9843
Epoch 58/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0703 - acc: 0.9881
Epoch 59/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0714 - acc: 0.9836
Epoch 60/400
1340/1340 [==============================] - 0s 55us/step - loss: 0.0731 - acc: 0.9828
Epoch 61/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0728 - acc: 0.9851
Epoch 62/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0701 - acc: 0.9881
Epoch 63/400


1340/1340 [==============================] - 0s 53us/step - loss: 0.0708 - acc: 0.9858
Epoch 78/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0711 - acc: 0.9851
Epoch 79/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0688 - acc: 0.9851
Epoch 80/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0707 - acc: 0.9858
Epoch 81/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0694 - acc: 0.9866
Epoch 82/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0703 - acc: 0.9873
Epoch 83/400
1340/1340 [==============================] - 0s 54us/step - loss: 0.0706 - acc: 0.9851
Epoch 84/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0704 - acc: 0.9828
Epoch 85/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0702 - acc: 0.9881
Epoch 86/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0723 - acc: 0.9836
Epoch 87/400


1340/1340 [==============================] - 0s 52us/step - loss: 0.0709 - acc: 0.9881
Epoch 102/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0698 - acc: 0.9888
Epoch 103/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0699 - acc: 0.9866
Epoch 104/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0690 - acc: 0.9858
Epoch 105/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0697 - acc: 0.9866
Epoch 106/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0713 - acc: 0.9858
Epoch 107/400
1340/1340 [==============================] - 0s 55us/step - loss: 0.0682 - acc: 0.9873
Epoch 108/400
1340/1340 [==============================] - 0s 55us/step - loss: 0.0701 - acc: 0.9896
Epoch 109/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0700 - acc: 0.9873
Epoch 110/400
1340/1340 [==============================] - 0s 54us/step - loss: 0.0699 - acc: 0.9873
Epoc

1340/1340 [==============================] - 0s 55us/step - loss: 0.0685 - acc: 0.9858
Epoch 126/400
1340/1340 [==============================] - 0s 56us/step - loss: 0.0693 - acc: 0.9866
Epoch 127/400
1340/1340 [==============================] - 0s 44us/step - loss: 0.0675 - acc: 0.9866
Epoch 128/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0690 - acc: 0.9843
Epoch 129/400
1340/1340 [==============================] - 0s 54us/step - loss: 0.0675 - acc: 0.9888
Epoch 130/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0701 - acc: 0.9843
Epoch 131/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0689 - acc: 0.9866
Epoch 132/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0692 - acc: 0.9858
Epoch 133/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0687 - acc: 0.9873
Epoch 134/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0674 - acc: 0.9873
Epoc

Epoch 150/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0667 - acc: 0.9888
Epoch 151/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0695 - acc: 0.9858
Epoch 152/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0673 - acc: 0.9903
Epoch 153/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0674 - acc: 0.9896
Epoch 154/400
1340/1340 [==============================] - 0s 57us/step - loss: 0.0677 - acc: 0.9866
Epoch 155/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0677 - acc: 0.9866
Epoch 156/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0675 - acc: 0.9888
Epoch 157/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0672 - acc: 0.9873
Epoch 158/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0677 - acc: 0.9866
Epoch 159/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0698 - ac

Epoch 174/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0689 - acc: 0.9866
Epoch 175/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0682 - acc: 0.9858
Epoch 176/400
1340/1340 [==============================] - 0s 54us/step - loss: 0.0680 - acc: 0.9858
Epoch 177/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0677 - acc: 0.9873
Epoch 178/400
1340/1340 [==============================] - 0s 54us/step - loss: 0.0677 - acc: 0.9851
Epoch 179/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0688 - acc: 0.9836
Epoch 180/400
1340/1340 [==============================] - 0s 53us/step - loss: 0.0672 - acc: 0.9873
Epoch 181/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0671 - acc: 0.9881
Epoch 182/400
1340/1340 [==============================] - 0s 53us/step - loss: 0.0656 - acc: 0.9881
Epoch 183/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0672 - ac

1340/1340 [==============================] - 0s 53us/step - loss: 0.0661 - acc: 0.9866
Epoch 199/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0664 - acc: 0.9851
Epoch 200/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0656 - acc: 0.9851
Epoch 201/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0669 - acc: 0.9873
Epoch 202/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0660 - acc: 0.9881
Epoch 203/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0661 - acc: 0.9873
Epoch 204/400
1340/1340 [==============================] - 0s 53us/step - loss: 0.0658 - acc: 0.9851
Epoch 205/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0662 - acc: 0.9881
Epoch 206/400
1340/1340 [==============================] - 0s 53us/step - loss: 0.0668 - acc: 0.9888
Epoch 207/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0647 - acc: 0.9873
Epoc

1340/1340 [==============================] - 0s 49us/step - loss: 0.0647 - acc: 0.9873
Epoch 223/400
1340/1340 [==============================] - 0s 53us/step - loss: 0.0662 - acc: 0.9888
Epoch 224/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0657 - acc: 0.9881
Epoch 225/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0635 - acc: 0.9873
Epoch 226/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0652 - acc: 0.9866
Epoch 227/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0669 - acc: 0.9843
Epoch 228/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0657 - acc: 0.9866
Epoch 229/400
1340/1340 [==============================] - 0s 58us/step - loss: 0.0654 - acc: 0.9881
Epoch 230/400
1340/1340 [==============================] - 0s 53us/step - loss: 0.0643 - acc: 0.9903
Epoch 231/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0644 - acc: 0.9888
Epoc

Epoch 246/400
1340/1340 [==============================] - 0s 55us/step - loss: 0.0653 - acc: 0.9903
Epoch 247/400
1340/1340 [==============================] - 0s 45us/step - loss: 0.0654 - acc: 0.9866
Epoch 248/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0651 - acc: 0.9888
Epoch 249/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0637 - acc: 0.9866
Epoch 250/400
1340/1340 [==============================] - 0s 53us/step - loss: 0.0650 - acc: 0.9888
Epoch 251/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0681 - acc: 0.9821
Epoch 252/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0641 - acc: 0.9866
Epoch 253/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0656 - acc: 0.9873
Epoch 254/400
1340/1340 [==============================] - 0s 57us/step - loss: 0.0627 - acc: 0.9888
Epoch 255/400
1340/1340 [==============================] - 0s 55us/step - loss: 0.0672 - ac

1340/1340 [==============================] - 0s 47us/step - loss: 0.0677 - acc: 0.9858
Epoch 271/400
1340/1340 [==============================] - 0s 54us/step - loss: 0.0647 - acc: 0.9896
Epoch 272/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0654 - acc: 0.9881
Epoch 273/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0645 - acc: 0.9888
Epoch 274/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0641 - acc: 0.9888
Epoch 275/400
1340/1340 [==============================] - 0s 45us/step - loss: 0.0643 - acc: 0.9888
Epoch 276/400
1340/1340 [==============================] - 0s 54us/step - loss: 0.0650 - acc: 0.9881
Epoch 277/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0662 - acc: 0.9896
Epoch 278/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0649 - acc: 0.9881
Epoch 279/400
1340/1340 [==============================] - 0s 44us/step - loss: 0.0637 - acc: 0.9858
Epoc

1340/1340 [==============================] - 0s 54us/step - loss: 0.0628 - acc: 0.9866
Epoch 294/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0627 - acc: 0.9873
Epoch 295/400
1340/1340 [==============================] - 0s 55us/step - loss: 0.0626 - acc: 0.9896
Epoch 296/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0638 - acc: 0.9873
Epoch 297/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0635 - acc: 0.9873
Epoch 298/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0638 - acc: 0.9888
Epoch 299/400
1340/1340 [==============================] - 0s 54us/step - loss: 0.0617 - acc: 0.9888
Epoch 300/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0661 - acc: 0.9866
Epoch 301/400
1340/1340 [==============================] - 0s 57us/step - loss: 0.0638 - acc: 0.9873
Epoch 302/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0636 - acc: 0.9881
Epoc

Epoch 317/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0625 - acc: 0.9873
Epoch 318/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0645 - acc: 0.9881
Epoch 319/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0609 - acc: 0.9903
Epoch 320/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0612 - acc: 0.9896
Epoch 321/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0619 - acc: 0.9896
Epoch 322/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0617 - acc: 0.9881
Epoch 323/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0634 - acc: 0.9888
Epoch 324/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0626 - acc: 0.9888
Epoch 325/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0625 - acc: 0.9873
Epoch 326/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0655 - ac

1340/1340 [==============================] - 0s 47us/step - loss: 0.0611 - acc: 0.9903
Epoch 342/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0632 - acc: 0.9873
Epoch 343/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0611 - acc: 0.9910
Epoch 344/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0607 - acc: 0.9866
Epoch 345/400
1340/1340 [==============================] - 0s 53us/step - loss: 0.0625 - acc: 0.9896
Epoch 346/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0620 - acc: 0.9881
Epoch 347/400
1340/1340 [==============================] - 0s 61us/step - loss: 0.0614 - acc: 0.9888
Epoch 348/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0622 - acc: 0.9888
Epoch 349/400
1340/1340 [==============================] - 0s 52us/step - loss: 0.0615 - acc: 0.9881
Epoch 350/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0613 - acc: 0.9896
Epoc

1340/1340 [==============================] - 0s 50us/step - loss: 0.0624 - acc: 0.9873
Epoch 366/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0618 - acc: 0.9896
Epoch 367/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0624 - acc: 0.9873
Epoch 368/400
1340/1340 [==============================] - 0s 53us/step - loss: 0.0609 - acc: 0.9903
Epoch 369/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0620 - acc: 0.9828
Epoch 370/400
1340/1340 [==============================] - 0s 57us/step - loss: 0.0624 - acc: 0.9873
Epoch 371/400
1340/1340 [==============================] - 0s 49us/step - loss: 0.0610 - acc: 0.9881
Epoch 372/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0604 - acc: 0.9910
Epoch 373/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0620 - acc: 0.9881
Epoch 374/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0595 - acc: 0.9888
Epoc

1340/1340 [==============================] - 0s 46us/step - loss: 0.0587 - acc: 0.9933
Epoch 389/400
1340/1340 [==============================] - 0s 55us/step - loss: 0.0592 - acc: 0.9888
Epoch 390/400
1340/1340 [==============================] - 0s 47us/step - loss: 0.0607 - acc: 0.9896
Epoch 391/400
1340/1340 [==============================] - 0s 51us/step - loss: 0.0607 - acc: 0.9896
Epoch 392/400
1340/1340 [==============================] - 0s 48us/step - loss: 0.0613 - acc: 0.9881
Epoch 393/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0603 - acc: 0.9873
Epoch 394/400
1340/1340 [==============================] - 0s 46us/step - loss: 0.0595 - acc: 0.9888
Epoch 395/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0589 - acc: 0.9925
Epoch 396/400
1340/1340 [==============================] - 0s 45us/step - loss: 0.0598 - acc: 0.9896
Epoch 397/400
1340/1340 [==============================] - 0s 50us/step - loss: 0.0609 - acc: 0.9896
Epoc

In [59]:
## without changing optimizer , gave a value of 0.773 
model.compile (  optimizer = 'sgd'  ,loss ='binary_crossentropy' , metrics=['accuracy'])
model.fit(train_x , train_y , epochs = 200, batch_size = 15)

Epoch 1/200
1340/1340 [==============================] - 0s 180us/step - loss: 0.3246 - acc: 0.8649
Epoch 2/200
1340/1340 [==============================] - 0s 85us/step - loss: 0.3254 - acc: 0.8709
Epoch 3/200
1340/1340 [==============================] - 0s 87us/step - loss: 0.3302 - acc: 0.8612
Epoch 4/200
1340/1340 [==============================] - 0s 85us/step - loss: 0.3246 - acc: 0.8604
Epoch 5/200
1340/1340 [==============================] - 0s 83us/step - loss: 0.3178 - acc: 0.8731
Epoch 6/200
1340/1340 [==============================] - 0s 86us/step - loss: 0.3263 - acc: 0.8604
Epoch 7/200
1340/1340 [==============================] - 0s 87us/step - loss: 0.3274 - acc: 0.8642
Epoch 8/200
1340/1340 [==============================] - 0s 86us/step - loss: 0.3183 - acc: 0.8716
Epoch 9/200
1340/1340 [==============================] - 0s 90us/step - loss: 0.3178 - acc: 0.8619
Epoch 10/200
1340/1340 [==============================] - 0s 77us/step - loss: 0.3115 - acc: 0.8716
Epoch 11

Epoch 23/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.3053 - acc: 0.8657
Epoch 24/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2966 - acc: 0.8731
Epoch 25/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2995 - acc: 0.8761
Epoch 26/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.3008 - acc: 0.8739
Epoch 27/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2948 - acc: 0.8724
Epoch 28/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.3013 - acc: 0.8634
Epoch 29/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.3022 - acc: 0.8754
Epoch 30/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2904 - acc: 0.8851
Epoch 31/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2958 - acc: 0.8784
Epoch 32/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.2966 - acc:

1340/1340 [==============================] - 0s 102us/step - loss: 0.2837 - acc: 0.8821
Epoch 45/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2817 - acc: 0.8851
Epoch 46/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2747 - acc: 0.8910
Epoch 47/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2800 - acc: 0.8799
Epoch 48/200
1340/1340 [==============================] - 0s 112us/step - loss: 0.2806 - acc: 0.8896
Epoch 49/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.2749 - acc: 0.8955
Epoch 50/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2795 - acc: 0.8910
Epoch 51/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2833 - acc: 0.8843
Epoch 52/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2728 - acc: 0.8903
Epoch 53/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2747 - acc: 0.8933
Epo

1340/1340 [==============================] - 0s 96us/step - loss: 0.2775 - acc: 0.8828
Epoch 66/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2720 - acc: 0.8858
Epoch 67/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2675 - acc: 0.8866
Epoch 68/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2649 - acc: 0.8918
Epoch 69/200
1340/1340 [==============================] - 0s 97us/step - loss: 0.2634 - acc: 0.8948
Epoch 70/200
1340/1340 [==============================] - 0s 99us/step - loss: 0.2728 - acc: 0.8858
Epoch 71/200
1340/1340 [==============================] - 0s 109us/step - loss: 0.2682 - acc: 0.8903
Epoch 72/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2668 - acc: 0.8903
Epoch 73/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2632 - acc: 0.8970
Epoch 74/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2594 - acc: 0.8925
Epoch 7

1340/1340 [==============================] - 0s 104us/step - loss: 0.2543 - acc: 0.8940
Epoch 87/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2635 - acc: 0.8873
Epoch 88/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2587 - acc: 0.8978
Epoch 89/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2464 - acc: 0.8948
Epoch 90/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.2594 - acc: 0.8910
Epoch 91/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2594 - acc: 0.8955
Epoch 92/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2527 - acc: 0.8970
Epoch 93/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2594 - acc: 0.8940
Epoch 94/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2569 - acc: 0.8955
Epoch 95/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2573 - acc: 0.8896
Epo

1340/1340 [==============================] - 0s 110us/step - loss: 0.2427 - acc: 0.9045
Epoch 108/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2520 - acc: 0.9007
Epoch 109/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2438 - acc: 0.8978
Epoch 110/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.2507 - acc: 0.8993
Epoch 111/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2439 - acc: 0.8985
Epoch 112/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2464 - acc: 0.8978
Epoch 113/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2489 - acc: 0.8963
Epoch 114/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.2499 - acc: 0.8970
Epoch 115/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2445 - acc: 0.9000
Epoch 116/200
1340/1340 [==============================] - 0s 108us/step - loss: 0.2475 - acc: 0.

1340/1340 [==============================] - 0s 105us/step - loss: 0.2352 - acc: 0.9067
Epoch 129/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2344 - acc: 0.9030
Epoch 130/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2443 - acc: 0.9037
Epoch 131/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2386 - acc: 0.8978
Epoch 132/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2369 - acc: 0.9052
Epoch 133/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2330 - acc: 0.9104
Epoch 134/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2381 - acc: 0.8978
Epoch 135/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2415 - acc: 0.8896
Epoch 136/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2349 - acc: 0.9037
Epoch 137/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2370 - acc: 0.90

1340/1340 [==============================] - 0s 103us/step - loss: 0.2326 - acc: 0.9000
Epoch 150/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.2256 - acc: 0.9090
Epoch 151/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2267 - acc: 0.9060
Epoch 152/200
1340/1340 [==============================] - 0s 109us/step - loss: 0.2367 - acc: 0.9075
Epoch 153/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2313 - acc: 0.9015
Epoch 154/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2220 - acc: 0.9112
Epoch 155/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2273 - acc: 0.9075
Epoch 156/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2282 - acc: 0.9075
Epoch 157/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2316 - acc: 0.9075
Epoch 158/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2262 - acc: 0.

1340/1340 [==============================] - 0s 105us/step - loss: 0.2150 - acc: 0.9142
Epoch 171/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2187 - acc: 0.9157
Epoch 172/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2238 - acc: 0.9067
Epoch 173/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2200 - acc: 0.9060
Epoch 174/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2228 - acc: 0.9067
Epoch 175/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2266 - acc: 0.8955
Epoch 176/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2196 - acc: 0.9022
Epoch 177/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2221 - acc: 0.9097
Epoch 178/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2143 - acc: 0.9090
Epoch 179/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2232 - acc: 0.908

1340/1340 [==============================] - 0s 100us/step - loss: 0.2107 - acc: 0.9149
Epoch 192/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2206 - acc: 0.9030
Epoch 193/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2091 - acc: 0.9112
Epoch 194/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2099 - acc: 0.9179
Epoch 195/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2117 - acc: 0.9104
Epoch 196/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2131 - acc: 0.9067
Epoch 197/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2207 - acc: 0.9052
Epoch 198/200
1340/1340 [==============================] - 0s 97us/step - loss: 0.2099 - acc: 0.9187
Epoch 199/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2100 - acc: 0.9090
Epoch 200/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2097 - acc: 0.909

In [62]:
# without changing optimizer
trained_out = model.evaluate (test_x , test_y)
print(trained_out)

660/660 [==============================] - 0s 34us/step
[0.49056715206666424, 0.8121212121212121]


In [20]:
# After Changing optimizer
trained_out = model.evaluate (test_x , test_y)
print(trained_out)

# seems like overfitting

660/660 [==============================] - 0s 71us/step
[1.0839965242328067, 0.7818181821794221]


In [29]:
# LSTM
trained_out = model.evaluate (test_x , test_y)
print(trained_out)



660/660 [==============================] - 0s 345us/step
[0.37668709827191904, 0.8621212128436927]


In [57]:
# LSTM iterati 2
trained_out = model.evaluate (test_x , test_y)
print(trained_out)



660/660 [==============================] - 0s 145us/step
[0.34184381040659817, 0.8666666673891472]


In [58]:
predic = np.round( model.predict(enc_test) ) 
print(predic)

[[1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.

In [0]:
save_test =pd.DataFrame(predic)
save_test.to_csv("test_check_lstm_2.csv")
files.download("test_check_lstm_2.csv")


In [0]:
Dense?