In [0]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from google.colab import files
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D 
from keras.utils import to_categorical
from keras.utils import np_utils
import io 
import csv

In [26]:
file_train=files.upload()

Saving train.csv to train (2).csv


In [0]:
# CSV read and 1 hot , using pandas to read

# read as dataframe df_train
df_train= pd.read_csv(io.StringIO(file_train['train.csv'].decode('utf-8')))

# if none fill with NAN
df_train.fillna(0,inplace=True)


In [34]:
# debug statement to check if it works
print(df_train)

        id        sequence  label
0        0  GTAGCGGCGCATGC      1
1        1  GCCTGCCACTTCCT      1
2        2  GAGAGGAGGGGTGT      1
3        3  GGGCAGGGCCGAGG      1
4        4  AGACGGGCCGCGCC      1
5        5  CTAGGCCGGAGCGT      1
6        6  AGGAGGCGGAGGGA      1
7        7  GCGTAGGGAGGCGG      1
8        8  ACCTCTGATCATTC      1
9        9  AGCAAGAACAGCAC      1
10      10  AGCCCCCGGAGGGA      1
11      11  GCCATCGCCAACTT      1
12      12  CGAAAGATTCGAAA      1
13      13  AGGAGGGCGGGAGA      1
14      14  TGGGGCGGAGCCAT      1
15      15  CCGCTCGTCGGCTG      1
16      16  GGCCGCGCCCACCA      1
17      17  GGTGCGGCGAGCGG      1
18      18  GCGCAGCCTTATCC      1
19      19  GCGGCCAGATGGGG      1
20      20  TGGGGGCGTAGCGC      1
21      21  GCGCGGCGAGGAGA      1
22      22  GGGAGGCGTGGCGC      1
23      23  GTCGTGGGCCGTGG      1
24      24  TTTGCCCTCCCCCT      1
25      25  GCGGCGGGCCCGGG      1
26      26  CGAGGGCTGGGCCG      1
27      27  GTTGGGCCGAAACA      1
28      28  GC

In [0]:
seq=df_train['sequence']
label=df_train['label']

base={
    'A':0,
    'G':1,
    'C':2,
    'T':3
     }
enc=np.zeros( (2000,14) )

for i in range(2000):
  enc[i]= [ base[ch] for ch in seq[i]]
  enc[i]=np.transpose(enc[i])
 
encode=to_categorical(enc)



In [0]:
train_test_split?

In [0]:
# using sk's train_test_split

train_x , test_x , train_y ,test_y = train_test_split(enc , label ,test_size =0.33 )

In [38]:
# Debug check for 1hot enc
print(encode[0][:][:])
print(seq[0])

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
GTAGCGGCGCATGC


In [32]:
file_test=files.upload()

Saving test.csv to test.csv


In [0]:
## Doing the same for test data


# read as dataframe df_test
df_test= pd.read_csv(io.StringIO(file_test['test.csv'].decode('utf-8')))

# if none fill with NAN
df_test.fillna(0,inplace=True)

seq_test = df_test['sequence']

enc_test=np.zeros( (400,14) )

for i in range(400):
  enc_test[i]= [base[k] for k in seq_test[i] ]


In [0]:
model = Sequential()
model.add(Dense(20, input_dim =14, activation ='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))
          

In [59]:
model.compile (  optimizer = 'sgd'  ,loss ='binary_crossentropy' , metrics=['accuracy'])
model.fit(train_x , train_y , epochs = 200, batch_size = 15)

Epoch 1/200
1340/1340 [==============================] - 0s 180us/step - loss: 0.3246 - acc: 0.8649
Epoch 2/200
1340/1340 [==============================] - 0s 85us/step - loss: 0.3254 - acc: 0.8709
Epoch 3/200
1340/1340 [==============================] - 0s 87us/step - loss: 0.3302 - acc: 0.8612
Epoch 4/200
1340/1340 [==============================] - 0s 85us/step - loss: 0.3246 - acc: 0.8604
Epoch 5/200
1340/1340 [==============================] - 0s 83us/step - loss: 0.3178 - acc: 0.8731
Epoch 6/200
1340/1340 [==============================] - 0s 86us/step - loss: 0.3263 - acc: 0.8604
Epoch 7/200
1340/1340 [==============================] - 0s 87us/step - loss: 0.3274 - acc: 0.8642
Epoch 8/200
1340/1340 [==============================] - 0s 86us/step - loss: 0.3183 - acc: 0.8716
Epoch 9/200
1340/1340 [==============================] - 0s 90us/step - loss: 0.3178 - acc: 0.8619
Epoch 10/200
1340/1340 [==============================] - 0s 77us/step - loss: 0.3115 - acc: 0.8716
Epoch 11

Epoch 23/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.3053 - acc: 0.8657
Epoch 24/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2966 - acc: 0.8731
Epoch 25/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2995 - acc: 0.8761
Epoch 26/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.3008 - acc: 0.8739
Epoch 27/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2948 - acc: 0.8724
Epoch 28/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.3013 - acc: 0.8634
Epoch 29/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.3022 - acc: 0.8754
Epoch 30/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2904 - acc: 0.8851
Epoch 31/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2958 - acc: 0.8784
Epoch 32/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.2966 - acc:

1340/1340 [==============================] - 0s 102us/step - loss: 0.2837 - acc: 0.8821
Epoch 45/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2817 - acc: 0.8851
Epoch 46/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2747 - acc: 0.8910
Epoch 47/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2800 - acc: 0.8799
Epoch 48/200
1340/1340 [==============================] - 0s 112us/step - loss: 0.2806 - acc: 0.8896
Epoch 49/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.2749 - acc: 0.8955
Epoch 50/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2795 - acc: 0.8910
Epoch 51/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2833 - acc: 0.8843
Epoch 52/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2728 - acc: 0.8903
Epoch 53/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2747 - acc: 0.8933
Epo

1340/1340 [==============================] - 0s 96us/step - loss: 0.2775 - acc: 0.8828
Epoch 66/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2720 - acc: 0.8858
Epoch 67/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2675 - acc: 0.8866
Epoch 68/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2649 - acc: 0.8918
Epoch 69/200
1340/1340 [==============================] - 0s 97us/step - loss: 0.2634 - acc: 0.8948
Epoch 70/200
1340/1340 [==============================] - 0s 99us/step - loss: 0.2728 - acc: 0.8858
Epoch 71/200
1340/1340 [==============================] - 0s 109us/step - loss: 0.2682 - acc: 0.8903
Epoch 72/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2668 - acc: 0.8903
Epoch 73/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2632 - acc: 0.8970
Epoch 74/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2594 - acc: 0.8925
Epoch 7

1340/1340 [==============================] - 0s 104us/step - loss: 0.2543 - acc: 0.8940
Epoch 87/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2635 - acc: 0.8873
Epoch 88/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2587 - acc: 0.8978
Epoch 89/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2464 - acc: 0.8948
Epoch 90/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.2594 - acc: 0.8910
Epoch 91/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2594 - acc: 0.8955
Epoch 92/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2527 - acc: 0.8970
Epoch 93/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2594 - acc: 0.8940
Epoch 94/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2569 - acc: 0.8955
Epoch 95/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2573 - acc: 0.8896
Epo

1340/1340 [==============================] - 0s 110us/step - loss: 0.2427 - acc: 0.9045
Epoch 108/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2520 - acc: 0.9007
Epoch 109/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2438 - acc: 0.8978
Epoch 110/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.2507 - acc: 0.8993
Epoch 111/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2439 - acc: 0.8985
Epoch 112/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2464 - acc: 0.8978
Epoch 113/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2489 - acc: 0.8963
Epoch 114/200
1340/1340 [==============================] - 0s 106us/step - loss: 0.2499 - acc: 0.8970
Epoch 115/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2445 - acc: 0.9000
Epoch 116/200
1340/1340 [==============================] - 0s 108us/step - loss: 0.2475 - acc: 0.

1340/1340 [==============================] - 0s 105us/step - loss: 0.2352 - acc: 0.9067
Epoch 129/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2344 - acc: 0.9030
Epoch 130/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2443 - acc: 0.9037
Epoch 131/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2386 - acc: 0.8978
Epoch 132/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2369 - acc: 0.9052
Epoch 133/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2330 - acc: 0.9104
Epoch 134/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2381 - acc: 0.8978
Epoch 135/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2415 - acc: 0.8896
Epoch 136/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2349 - acc: 0.9037
Epoch 137/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2370 - acc: 0.90

1340/1340 [==============================] - 0s 103us/step - loss: 0.2326 - acc: 0.9000
Epoch 150/200
1340/1340 [==============================] - 0s 104us/step - loss: 0.2256 - acc: 0.9090
Epoch 151/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2267 - acc: 0.9060
Epoch 152/200
1340/1340 [==============================] - 0s 109us/step - loss: 0.2367 - acc: 0.9075
Epoch 153/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2313 - acc: 0.9015
Epoch 154/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2220 - acc: 0.9112
Epoch 155/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2273 - acc: 0.9075
Epoch 156/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2282 - acc: 0.9075
Epoch 157/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2316 - acc: 0.9075
Epoch 158/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2262 - acc: 0.

1340/1340 [==============================] - 0s 105us/step - loss: 0.2150 - acc: 0.9142
Epoch 171/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2187 - acc: 0.9157
Epoch 172/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2238 - acc: 0.9067
Epoch 173/200
1340/1340 [==============================] - 0s 103us/step - loss: 0.2200 - acc: 0.9060
Epoch 174/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2228 - acc: 0.9067
Epoch 175/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2266 - acc: 0.8955
Epoch 176/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2196 - acc: 0.9022
Epoch 177/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2221 - acc: 0.9097
Epoch 178/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2143 - acc: 0.9090
Epoch 179/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2232 - acc: 0.908

1340/1340 [==============================] - 0s 100us/step - loss: 0.2107 - acc: 0.9149
Epoch 192/200
1340/1340 [==============================] - 0s 98us/step - loss: 0.2206 - acc: 0.9030
Epoch 193/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2091 - acc: 0.9112
Epoch 194/200
1340/1340 [==============================] - 0s 100us/step - loss: 0.2099 - acc: 0.9179
Epoch 195/200
1340/1340 [==============================] - 0s 101us/step - loss: 0.2117 - acc: 0.9104
Epoch 196/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2131 - acc: 0.9067
Epoch 197/200
1340/1340 [==============================] - 0s 102us/step - loss: 0.2207 - acc: 0.9052
Epoch 198/200
1340/1340 [==============================] - 0s 97us/step - loss: 0.2099 - acc: 0.9187
Epoch 199/200
1340/1340 [==============================] - 0s 96us/step - loss: 0.2100 - acc: 0.9090
Epoch 200/200
1340/1340 [==============================] - 0s 105us/step - loss: 0.2097 - acc: 0.909

In [62]:
trained_out = model.evaluate (test_x , test_y)
print(trained_out)

660/660 [==============================] - 0s 34us/step
[0.49056715206666424, 0.8121212121212121]


In [79]:
predic = np.round( model.predict(enc_test) ) 
print(predic)

[[1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.

In [0]:
save_test =pd.DataFrame(predic)
save_test.to_csv("test_check.csv")
files.download("test_check.csv")


In [0]:
with open('mycsv.csv', 'w' , newline = '') as f:
  writer = csv.writer(f)
  writer.writerow(['col1', 'col2' , 'col3'])
  writer.writerow(['one', 'two', 'three'])

In [0]:
Dense?